kafka-config:
  schema-registry-url-key: schema.registry.url
  num-of-partitions: 3
  topic-names-to-create: twitter-topic
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  topic-name: twitter-topic
  schema-registry-url: http://localhost:8081
  replication-factor: 3
kafka-producer-config:
  batch-size-boost-factor: 100
  linger-ms: 5
  batch-size: 16384
  retry-count: 5
  request-timeout-ms: 60000
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  key-serializer-class: org.apache.kafka.common.serialization.LongSerializer
  compression-type: snappy
  acks: all
twitter-to-kafka-service:
  mock-min-tweet-length: 5
  welcome-message: Hello microservices!
  enable-mock-tweets: true
  twitter-keywords: Java, Microservices, Kafka, Elasticsearch
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000
retry-config:
  max-interval-ms: 10000
  max-attempts: 3
  initial-interval-ms: 1000
  sleep-time-ms: 2000
  multiplier: 2.0
server:
  port: 8181
spring:
  cloud:
    compatibility-verifier:
      enabled: false
